src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Experience__c</fullName>
        <label>Experience</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tertiary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Engine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Engine</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Family</field>
                <operation>equals</operation>
                <value>Engine</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Engine</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exhaust__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exhaust</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Family</field>
                <operation>equals</operation>
                <value>Exhaust</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Exhaust)</relationshipLabel>
        <relationshipName>Exhaust</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gauge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gauge</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Family</field>
                <operation>equals</operation>
                <value>Gauge</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Gauge)</relationshipLabel>
        <relationshipName>Gauge</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Head_Light__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Head Light</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Family</field>
                <operation>equals</operation>
                <value>Head Light</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Head Light)</relationshipLabel>
        <relationshipName>Head_Light</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LogoOrSticker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LogoOrSticker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Family</field>
                <operation>equals</operation>
                <value>LogoOrSticker</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (LogoOrSticker)</relationshipLabel>
        <relationshipName>LogoOrSticker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mirror__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mirror</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Family</field>
                <operation>equals</operation>
                <value>Mirrors</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Mirror)</relationshipLabel>
        <relationshipName>Mirror</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stock__c</fullName>
        <label>Stock</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tail_Light__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tail Light</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Family</field>
                <operation>equals</operation>
                <value>Rear Light</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Tail Light)</relationshipLabel>
        <relationshipName>Tail_Light</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Turn_Signal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Turn Signal</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Family</field>
                <operation>equals</operation>
                <value>Turn Signal</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Turn Signal)</relationshipLabel>
        <relationshipName>Turn_Signal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wheel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wheel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Family</field>
                <operation>equals</operation>
                <value>Wheel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Wheel)</relationshipLabel>
        <relationshipName>Wheel</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/GoelBikers_TestDataFactory.cls
@isTest
public class GoelBikers_TestDataFactory {
    public static void generateGoelBikersTestData(){
    	Pricebook2 standardPricebook = new Pricebook2(Id = Test.getStandardPricebookId() , IsActive = true);
		update standardPricebook;
		Account accountObj = new Account(Name = 'AccountA' , Email_Address__c = 'a@b.c');
		insert accountObj;
		Contact contactObj = new Contact(LastName = 'ContactA' , Experience__c = 30 , AccountId = accountObj.Id , Level__c = 'Primary' , Email = 'c@b.a');
		insert contactObj;
		Opportunity opportunityObj = new Opportunity(Name = 'OpportunityA' , AccountId = accountObj.Id , StageName = 'Prospecting' , CloseDate = System.today());
		insert opportunityObj;
    	Product2 wheel = new Product2(Name='wheel' , Stock__c = 10 , Family = 'Wheel');
		insert wheel;
		Product2 engine = new Product2(Name='engine' , Stock__c = 10 , Family = 'Engine');
		insert engine;
		Product2 exhaust = new Product2(Name='exhaust' , Stock__c = 10 , Family = 'Exhaust');
		insert exhaust;
		Product2 mirror = new Product2(Name='mirror' , Stock__c = 10 , Family = 'Mirror');
		insert mirror;
		Product2 head = new Product2(Name='head' , Stock__c = 10 , Family = 'Head Light');
		insert head;
		Product2 turn = new Product2(Name='turn' , Stock__c = 10 , Family = 'Turn Signal');
		insert turn;
		Product2 tail = new Product2(Name='tail' , Stock__c = 10 , Family = 'Rear Light');
		insert tail;
		Product2 logo = new Product2(Name='logo' , Stock__c = 10 , Family = 'LogoOrSticker');
		insert logo;
		Product2 gauge = new Product2(Name='gauge' , Stock__c = 10 , Family = 'Gauge');
		insert gauge;
		Product2 bike = new Product2(Name='bike' , Wheel__c = wheel.Id , Turn_Signal__c = turn.Id , Tail_Light__c = tail.Id , Mirror__c = mirror.Id , LogoOrSticker__c = logo.Id , Head_Light__c = head.Id , Gauge__c = gauge.Id , Exhaust__c = exhaust.Id , Engine__c = engine.Id , Deal__c = opportunityObj.Id);
		insert bike;
		System.debug(bike);
    }
}