src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <label>Transaction Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Experience__c</fullName>
        <label>Experience</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EFT_Transaction_Status__c.object
<CustomObject>
    <fields>
        <fullName>Method_Name__c</fullName>
        <label>Method Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Card Address Verify</fullName>
                </value>
                <value>
                    <fullName>Credit Card PIN Verify</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesHeader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SalesHeader</label>
        <referenceTo>SalesHeader__c</referenceTo>
        <relationshipLabel>EFT Transaction Status</relationshipLabel>
        <relationshipName>EFT_Transaction_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <label>Transaction Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>EFT Transaction Status</label>
    <nameField>
        <label>EFT  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EFT Transaction Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SalesHeader__c.object
<CustomObject>
    <fields>
        <fullName>Bill_to_Customer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SalesHeaders</relationshipLabel>
        <relationshipName>SalesHeaders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bill_to_Customer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Customer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SalesHeaders</relationshipLabel>
        <relationshipName>SalesHeaders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SalesHeader</label>
    <nameField>
        <displayFormat>SH-{0000}</displayFormat>
        <label>SalesHeader Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SalesHeaders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EFTAddressVerificationTriggerTest.cls
@istest
public class EFTAddressVerificationTriggerTest {
    public static testmethod void EFTAddressVerificationAfterInsertTest(){
        list<sObject> slist = new list<sObject>();
        Account acc = new account(name='acc');
        insert acc;
        System.debug(acc);
        Contact con = new contact(lastname='con',experience__c=10);
        insert con;
        System.debug(con);
        SalesHeader__c sh = new SalesHeader__c(Status__c='Open',Bill_to_Customer_Account__c=acc.id,Bill_to_Customer_Contact__c=con.id);
        insert sh;
        System.debug(sh);
        Group g = new Group(name='AVS',Type='Queue');
        insert g;
        System.debug(g);
        aggregateresult agg = [select count(id) from case];
        Integer beforeCount = (Integer)agg.get('expr0');
        EFT_Transaction_Status__c eft = new EFT_Transaction_Status__c(name='eft',method_name__c='Credit Card Address Verify',transaction_status__c='Declined',SalesHeader__c=sh.id);
        insert eft;
        case c = [select id from case];
        System.debug(c.id);
        agg = [select count(id) from case];
        Integer afterCount = (Integer)agg.get('expr0');
        System.assert(afterCount>beforeCount);
    }
}