src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order_Date__c</fullName>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Number__c</fullName>
        <label>Sales Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <label>Transaction Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Assignment</fullName>
        <active>true</active>
        <businessProcess>SP1</businessProcess>
        <label>Assignment</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EFT_Transaction_Status__c.object
<CustomObject>
    <fields>
        <fullName>SalesHeader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SalesHeader</label>
        <referenceTo>SalesHeader__c</referenceTo>
        <relationshipLabel>EFT Transaction Status</relationshipLabel>
        <relationshipName>EFT_Transaction_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <label>Transaction Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>EFT Transaction Status</label>
    <nameField>
        <label>EFT  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EFT Transaction Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SalesHeader__c.object
<CustomObject>
    <fields>
        <fullName>Bill_to_Customer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SalesHeaders</relationshipLabel>
        <relationshipName>SalesHeaders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bill_to_Customer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Customer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SalesHeaders</relationshipLabel>
        <relationshipName>SalesHeaders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SalesHeader</label>
    <nameField>
        <displayFormat>SH-{0000}</displayFormat>
        <label>SalesHeader Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SalesHeaders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EFTAddressVerificationTriggerHandler.cls
public class EFTAddressVerificationTriggerHandler {
    public static void EFTAddressVerificationAfterInsertHandler(list<EFT_Transaction_Status__c> eftlist){
        list<case> caselist = new list<case>();
        group g = [select Id from Group where Name = 'AVS' and Type = 'Queue' limit 1];
        for(EFT_Transaction_Status__c eft : eftlist){
            SalesHeader__c sh = [select Bill_to_Customer_Account__c,Bill_to_Customer_Contact__c,Bill_to_Customer_Account__r.name,name from SalesHeader__c where id =: eft.SalesHeader__c];
            String cType='Address Did Not Verify';
            caselist.add(new case(accountid=sh.Bill_to_Customer_Account__c,
                                  contactId=sh.Bill_to_Customer_Contact__c,
                                 recordtypeid=Schema.SObjectType.Case.getRecordTypeInfosByName().get('Assignment').getRecordTypeId(),
                                 origin='Internal',
                                 ownerid=g.id,
                                 reason='Address Did Not Verify	',
                                 priority='high',
                                 status='New',
                                 Type=cType,
                                 subject=sh.Bill_to_Customer_Account__r.name+' '+cType,
                                 Open_Sales_Order__c=eft.SalesHeader__c,
                                 Transaction_Status__c=eft.Transaction_Status__c,
                                 Sales_Order_Number__c=sh.Name,
                                 Order_Date__c=eft.Transaction_Date__c));
        }
        insert caselist;
        System.debug(caselist);
    }
}