src/objects/Google_Distance_Matrix_API_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Base_URL__c</fullName>
        <label>Base URL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Type__c</fullName>
        <label>Response Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sensor__c</fullName>
        <label>Sensor</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Google Distance Matrix API Setting</label>
</CustomObject>

src/objects/Survey_Appointment_Company_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>AssignTo_User__c</fullName>
        <label>AssignTo User</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Postal_Code__c</fullName>
        <label>Company Postal Code</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Subject__c</fullName>
        <label>Event Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reachable_Time_in_Seconds__c</fullName>
        <label>Reachable Time in Seconds</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey Appointment Company Setting</label>
</CustomObject>

src/objects/Survey_Appointment_Message_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>API_Failure_Message__c</fullName>
        <label>API Failure Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>API_Result_Failure_Message__c</fullName>
        <label>API Result Failure Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Failed_to_Reach_Message__c</fullName>
        <label>Failed to Reach Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Success_Message__c</fullName>
        <label>Success Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Today_Timeout_Message__c</fullName>
        <label>Today Timeout Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Survey Appointment Message Setting</label>
</CustomObject>

src/objects/Survey_Appointment_Time_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>End_Time_Hours__c</fullName>
        <label>End Time Hours</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Time_Minutes__c</fullName>
        <label>End Time Minutes</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Time_Hours__c</fullName>
        <label>Start Time Hours</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Time_Minutes__c</fullName>
        <label>Start Time Minutes</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time_Slot_Difference__c</fullName>
        <label>Time Slot Difference</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey Appointment Time Setting</label>
</CustomObject>

src/classes/SurveyAppointment_TestDataFactory.cls
@isTest
public class SurveyAppointment_TestDataFactory {
    public static void generateSurveyAppointmentCustomSettingTestData(){
    	Survey_Appointment_Time_Setting__c timeSetting = new Survey_Appointment_Time_Setting__c();
    	timeSetting.End_Time_Hours__c = 19; 
    	timeSetting.End_Time_Minutes__c = 30;
    	timeSetting.Start_Time_Hours__c = 7;
    	timeSetting.Start_Time_Minutes__c = 30;
    	timeSetting.Time_Slot_Difference__c = 30;
    	timeSetting.Name = 'Survey Appointment Time';
    	insert timeSetting;
    	Survey_Appointment_Company_Setting__c companySetting = new Survey_Appointment_Company_Setting__c();
    	companySetting.AssignTo_User__c = 'System Administrator';
    	companySetting.Company_Postal_Code__c = '411007';
    	companySetting.Event_Subject__c = 'Survey Appointment';
    	companySetting.Reachable_Time_in_Seconds__c = 18000;
    	companySetting.Name = 'Company Location';
    	insert companySetting;
    	Google_Distance_Matrix_API_Setting__c apiSetting = new Google_Distance_Matrix_API_Setting__c();
    	apiSetting.Base_URL__c = 'http://maps.googleapis.com/maps/api/distancematrix/';
    	apiSetting.Language__c = 'en-EN';
    	apiSetting.Response_Type__c = 'json';
    	apiSetting.Sensor__c = 'false';
    	apiSetting.Name = 'Google Distance Matrix API';
    	insert apiSetting;
    	Survey_Appointment_Message_Setting__c messageSetting = new Survey_Appointment_Message_Setting__c();
    	messageSetting.Name = 'Survey Appointment Message';
    	messageSetting.API_Failure_Message__c = 'Sorry..! We are unable to process your request. Please try again after some time. For further queries drop us an email at "support@xyzcompany.com" and we will be glad to assist you.';
    	messageSetting.API_Result_Failure_Message__c = 'Sorry..! We are unable to track the specified address. Please drop us an email at "support@xyzcompany.com" and we will be glad to assist you.';
    	messageSetting.Failed_to_Reach_Message__c = 'Sorry..! We are unable to reach you at the specified address. Please drop us an email at "support@xyzcompany.com" and we will be glad to assist you.';
    	messageSetting.Success_Message__c = 'Thank You. Your appointment is been booked. For any queries drop us an email at "support@xyzcompany.com" and we will be glad to assist you.';
    	messageSetting.Today_Timeout_Message__c = 'Sorry..! You can not book an appointment for today now. Please book an appointment for tommorrow. For further queries drop us an email at "support@xyzcompany.com" and we will be glad to assist you.';
    	insert messageSetting;
    }
    public static void generateSurveyAppointmentRecordTestData(){
    	User userObj = new User(LastName = 'ln' , Phone = '5684239' , Email = 'ln@user.com' , UserName = 'ln@user.com' , Alias = 'ln' , CommunityNickName = 'ln' , TimeZoneSIdKey = 'America/Los_Angeles' , LocaleSIdKey = 'en_US' , EmailEncodingKey = 'UTF-8', ProfileId = '00e7F000001TR4x' , LanguageLocaleKey = 'en_US');
    	insert userObj;
    	Contact contactObj = new Contact(LastName = 'Mandhare' , email = 's@m.com');
    	insert contactObj;
    	Event eventObj = new Event(OwnerId = userObj.Id , Subject = 'Survey Appointment' , StartDateTime = DateTime.newInstance(System.today() , Time.newInstance(15,0,0,0)) , EndDateTime = DateTime.newInstance(System.today() , Time.newInstance(15,30,0,0)));
    	insert eventObj;
    }
}