src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Engine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Engine</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Family</field>
                <operation>equals</operation>
                <value>Engine</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Engine</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exhaust__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exhaust</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Family</field>
                <operation>equals</operation>
                <value>Exhaust</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Exhaust)</relationshipLabel>
        <relationshipName>Exhaust</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gauge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gauge</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Family</field>
                <operation>equals</operation>
                <value>Gauge</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Gauge)</relationshipLabel>
        <relationshipName>Gauge</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Head_Light__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Head Light</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Family</field>
                <operation>equals</operation>
                <value>Head Light</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Head Light)</relationshipLabel>
        <relationshipName>Head_Light</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LogoOrSticker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LogoOrSticker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Family</field>
                <operation>equals</operation>
                <value>LogoOrSticker</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (LogoOrSticker)</relationshipLabel>
        <relationshipName>LogoOrSticker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mirror__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mirror</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Family</field>
                <operation>equals</operation>
                <value>Mirrors</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Mirror)</relationshipLabel>
        <relationshipName>Mirror</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stock__c</fullName>
        <label>Stock</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tail_Light__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tail Light</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Family</field>
                <operation>equals</operation>
                <value>Rear Light</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Tail Light)</relationshipLabel>
        <relationshipName>Tail_Light</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Turn_Signal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Turn Signal</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Family</field>
                <operation>equals</operation>
                <value>Turn Signal</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Turn Signal)</relationshipLabel>
        <relationshipName>Turn_Signal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wheel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wheel</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Family</field>
                <operation>equals</operation>
                <value>Wheel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Wheel)</relationshipLabel>
        <relationshipName>Wheel</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/Add_Bike_Parts_Controller.cls
public with sharing class Add_Bike_Parts_Controller {
    public Product2 customBike;
    public List<Product2> accessoryList{get; set;}
    public boolean added{get; set;}
    public Add_Bike_Parts_Controller() {
    	accessoryList = new List<Product2>();
    	setCustomBike(apexpages.currentpage().getparameters().get('id'));
    	added = false;
    }
    public void setCustomBike(Id product2Id) {
    	customBike = [
    		SELECT Name
    			 , Wheel__c
    			 , Turn_Signal__c
    			 , Tail_Light__c
    			 , Mirror__c
    			 , LogoOrSticker__c
    			 , Head_Light__c
    			 , Gauge__c
    			 , Exhaust__c
    			 , Engine__c 
    		  From Product2 
    		 WHERE Id = :product2Id
    	];
    	if(customBike.Wheel__c!=null)
    		accessoryList.add([
    			SELECT Name
    			 	 , Stock__c 
    			  From Product2 
    			 WHERE Id = :customBike.Wheel__c
    		]);
		if(customBike.Turn_Signal__c!=null)
    		accessoryList.add([
    			SELECT Name
    				 , Stock__c 
    			  From Product2 
    			 WHERE Id = :customBike.Turn_Signal__c
    		]);
    	if(customBike.Tail_Light__c!=null)
    		accessoryList.add([
    			SELECT Name
    			 	 , Stock__c 
    			  From Product2 
    			 WHERE Id = :customBike.Tail_Light__c
    		]);
    	if(customBike.Mirror__c!=null)
    		accessoryList.add([
    			SELECT Name
    				 , Stock__c 
    			  From Product2 
    			 WHERE Id = :customBike.Mirror__c
    		]);
    	if(customBike.LogoOrSticker__c!=null)
    		accessoryList.add([
    			SELECT Name
    				 , Stock__c 
    			  From Product2 
    			 WHERE Id = :customBike.LogoOrSticker__c
    		]);
    	if(customBike.Head_Light__c!=null)
    		accessoryList.add([
    			SELECT Name
    				 , Stock__c 
    			  From Product2 
    			 WHERE Id = :customBike.Head_Light__c
    		]);
    	if(customBike.Gauge__c!=null)
    		accessoryList.add([
    			SELECT Name
    				 , Stock__c 
    			  From Product2 
    			 WHERE Id = :customBike.Gauge__c
    		]);
    	if(customBike.Exhaust__c!=null)
    		accessoryList.add([
    			SELECT Name
    				 , Stock__c 
    			  From Product2 
    			 WHERE Id = :customBike.Exhaust__c
    		]);
    	if(customBike.Engine__c!=null)
    		accessoryList.add([
    			SELECT Name
    				 , Stock__c 
    			  From Product2 
    			 WHERE Id = :customBike.Engine__c
    		]);
    }
    public void updateAccessoryList() {
    	List<Id> productIdList = new List<Id>();
    	for(Product2 productObj : accessoryList) {
    		productObj.Stock__c -= 1;
    		productIdList.add(productObj.Id);
    	}
    	added = true;
    	update accessoryList;
    	List<PriceBookEntry> priceBookEntryList = [
    		SELECT UnitPrice 
    		  FROM PriceBookEntry 
    		 WHERE Product2Id IN :productIdList
    	];
    	PriceBookEntry customBikePriceBookEntryObj = [
    		SELECT UnitPrice 
    		  FROM PriceBookEntry 
    		 WHERE Product2Id = :customBike.Id
    	];
    	for(PriceBookEntry priceBookEntryObj : priceBookEntryList)
    		customBikePriceBookEntryObj.UnitPrice += priceBookEntryObj.UnitPrice;
    	update customBikePriceBookEntryObj;
    }
    public Product2 getCustomBike() {
    	return customBike;
    }
}